name: Daily Commit

on:
  schedule:
    - cron: '5 1 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 23f3002495@ds.study.iitm.ac.in
        run: echo "Assignment step"

      - name: Make Commit
        run: |
          echo "$(date)" >> daily_update.txt
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add daily_update.txt
          git commit -m "Daily auto update $(date)"
          git push
